In [1]:
import pandas as pd
import numpy as np

In [2]:
## Step 1:
df = pd.read_excel("Data/Customer Call List.xlsx")

# Step 2:
# url = 'https://raw.githubusercontent.com/AlexTheAnalyst/PandasYouTubeSeries/main/Customer%20Call%20List.xlsx'
# df = pd.read_excel(url)

In [3]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [4]:
df.shape

(21, 8)

In [5]:
df.replace("N/a", np.nan, inplace=True)

In [6]:
df.isna().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         4
Address              1
Paying Customer      1
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

## Drop duplicate

In [7]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [8]:
df = df.drop_duplicates()

### Drop column

In [9]:
df = df.drop(columns= "Not_Useful_Column") # the column is not useful

### Formating lastName

In [10]:
# df["Last_Name"] = df["Last_Name"].str.replace(r"[^\w\s]|_", "", regex=True)
df["Last_Name"]= df["Last_Name"].str.strip("12345._/?>")

### Formmating phone

In [11]:
df["Phone_Number"]= df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:])

C:\Users\Admin\AppData\Local\Temp\ipykernel_13472\3191622483.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Phone_Number"]= df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

In [12]:
df["Phone_Number"].isna().sum()

0

### Splitting address

In [13]:
df[["Street_Address", "State", "Zip_code"]] = df["Address"].str.split(',',2, expand= True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13472\254897372.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[["Street_Address", "State", "Zip_code"]] = df["Address"].str.split(',',2, expand= True)

### Formatting paying Customer

In [14]:
df["Paying Customer"]= df["Paying Customer"].str.replace('Yes', 'Y')
df["Paying Customer"]= df["Paying Customer"].str.replace('No', 'N')

### Do not contact

In [15]:
df["Do_Not_Contact"]= df["Paying Customer"].str.replace('Yes', 'Y')
df["Do_Not_Contact"]= df["Paying Customer"].str.replace('No', 'N')

In [16]:
df.fillna('')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,Y,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,N,93 West Main Street,,
2,1003,Walter,White,nan--,298 Drugs Driveway,N,N,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,Y,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,nan--,123 Middle Earth,Y,Y,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,Y,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,Y,612 Shire Lane,Shire,
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,Y,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,Y,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,Y,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,Y,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,Y,3498 Super Lane,,
18,1019,Creed,Braton,nan--,,,,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,Y,910 Tatooine Road,Tatooine,

In [17]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,Y,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,N,93 West Main Street,None,None
2,1003,Walter,White,nan--,298 Drugs Driveway,N,N,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,Y,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,nan--,123 Middle Earth,Y,Y,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,Y,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,Y,612 Shire Lane,Shire,None
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,Y,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,Y,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,Y,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,Y,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,Y,3498 Super Lane,None,None
18,1019,Creed,Braton,nan--,NaN,NaN,NaN,NaN,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,Y,910 Tatooine Road,Tatooine,None

In [18]:
df.dropna(subset= "Phone_Number")#
# df.dropna()#

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,Y,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,N,93 West Main Street,None,None
2,1003,Walter,White,nan--,298 Drugs Driveway,N,N,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,Y,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,nan--,123 Middle Earth,Y,Y,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,Y,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,Y,612 Shire Lane,Shire,None
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,Y,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,Y,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,Y,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,Y,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,Y,3498 Super Lane,None,None
18,1019,Creed,Braton,nan--,NaN,NaN,NaN,NaN,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,Y,910 Tatooine Road,Tatooine,None

In [19]:
df.rename(columns={"Zip_code": "zip"})

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,Y,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,N,93 West Main Street,None,None
2,1003,Walter,White,nan--,298 Drugs Driveway,N,N,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,Y,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,nan--,123 Middle Earth,Y,Y,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,Y,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,Y,612 Shire Lane,Shire,None
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,Y,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,Y,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,Y,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,Y,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,Y,3498 Super Lane,None,None
18,1019,Creed,Braton,nan--,NaN,NaN,NaN,NaN,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,Y,910 Tatooine Road,Tatooine,None

In [20]:
##
df.sort_values(by=["First_Name"])

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,N,93 West Main Street,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,Y,910 Tatooine Road,Tatooine,None
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,Y,3498 Super Lane,None,None
18,1019,Creed,Braton,nan--,NaN,NaN,NaN,NaN,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,Y,2039 Main Street,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,Y,123 Shire Lane,Shire,None
8,1009,Gandalf,NaN,nan--,123 Middle Earth,Y,Y,123 Middle Earth,None,None
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,Y,2394 Hogwarts Avenue,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,None,None
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,Y,123 Dragons Road,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,Y,343 City Parkway,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,Y,121 Paper Avenue,Pennsylvania,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,Y,25th Main Street,New York,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,Y,612 Shire Lane,Shire,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
2,1003,Walter,White,nan--,298 Drugs Driveway,N,N,298 Drugs Driveway,None,None

In [21]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,Y,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,N,93 West Main Street,None,None
2,1003,Walter,White,nan--,298 Drugs Driveway,N,N,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,Y,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,nan--,123 Middle Earth,Y,Y,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,Y,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,Y,612 Shire Lane,Shire,None
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,Y,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,Y,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,Y,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,Y,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,Y,3498 Super Lane,None,None
18,1019,Creed,Braton,nan--,NaN,NaN,NaN,NaN,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,Y,910 Tatooine Road,Tatooine,None

In [22]:
df.iloc[2]

CustomerID                       1003
First_Name                     Walter
Last_Name                       White
Phone_Number                    nan--
Address            298 Drugs Driveway
Paying Customer                     N
Do_Not_Contact                      N
Street_Address     298 Drugs Driveway
State                            None
Zip_code                         None
Name: 2, dtype: object

### Pivot

In [23]:
df.pivot(index="CustomerID", columns="Phone_Number", values= "Do_Not_Contact")

Phone_Number,123-543-2345,123-545-5421,123-643-9775,304-762-2467,876-678-3469,nan--
CustomerID,,,,,,
1001,NaN,Y,NaN,NaN,NaN,NaN
1002,NaN,NaN,N,NaN,NaN,NaN
1003,NaN,NaN,NaN,NaN,NaN,N
1004,Y,NaN,NaN,NaN,NaN,NaN
1005,NaN,NaN,NaN,NaN,Y,NaN
1006,NaN,NaN,NaN,Y,NaN,NaN
1007,NaN,NaN,NaN,NaN,NaN,N
1008,NaN,NaN,NaN,NaN,N,NaN
1009,NaN,NaN,NaN,NaN,NaN,Y
1010,NaN,Y,NaN,NaN,NaN,NaN
1011,NaN,NaN,NaN,NaN,NaN,Y
1012,NaN,NaN,NaN,NaN,NaN,Y
1013,Y,NaN,NaN,NaN,NaN,NaN
1014,NaN,NaN,NaN,NaN,Y,NaN
1015,NaN,NaN,NaN,N,NaN,NaN
1016,NaN,N,NaN,NaN,NaN,NaN
1017,NaN,NaN,Y,NaN,NaN,NaN
1018,NaN,NaN,NaN,NaN,NaN,Y
1019,NaN,NaN,NaN,NaN,NaN,NaN
1020,NaN,NaN,NaN,NaN,Y,NaN